### ISSUE TITLE
Welcome to join our group. Please write on your Github ID, then I invite you.

### ISSUE THREAD

**Issue by diguage** [mntfun/docs#1]
We are the readers of Zuoertingfeng. 
We want to form some teams in order to competiting the code.
*Welcome to join our group. Please write on your Github ID, then I invite you. *

**Comment by wang7x** [comment]
wang7x, 3q

**Comment by SmartBrave** [comment]
I'm the fans of ZuoErTingFeng，and I want to join you . My Github ID is : [SmartBrave](https://github.com/SmartBrave/), please invite me, thanks a lot.

**Comment by v2panda** [comment]
[v2panda](https://github.com/v2panda),please invite me, thanks a lot.

**Comment by nickyzhi** [comment]
@nickyzhi, thanks

**Comment by Logphi** [comment]
Logphi，thanks a lot.

**Comment by TaylorWu** [comment]
TaylorWu, thanks a lot.

**Comment by binderclip** [comment]
binderclip, thx.

**Comment by fanlinchong** [comment]
fanlinchong, please invite me,thinks.

**Comment by Junho2009** [comment]
Junho2009, thx.
Info: Junho - game developer

**Comment by zhangdingsong** [comment]
zhangdingsong, thx a lot!

**Comment by eveshi** [comment]
@eveshi, thank you so much

**Comment by brutalmraz** [comment]
brutalmraz,  thx

**Comment by CloudFeng** [comment]
DGua please invite me，thanks！

**Comment by reposkeeper** [comment]
reposkeeper, thx ~

**Comment by baobao219** [comment]
baobao219,please invite me, thanks a lot.

**Comment by AhianZhang** [comment]
ID:AhainZhang    
thx

**Comment by luabijam** [comment]
luabijam, thx

**Comment by XiangNanLi** [comment]
[https://github.com/XiangNanLi](XiangNanLi)
thanks very much!

**Comment by XiangNanLi** [comment]
[XiangNanLi](https://github.com/XiangNanLi)
thanks very much!

**Comment by cattcatt1987** [comment]
cattcatt1987，thx

**Comment by codeyu** [comment]
codeyu，thx

**Comment by orange90** [comment]
orange90, thx

**Comment by GaoLiaoLiao** [comment]
GaoLiaoLiao   thx

**Comment by wangyongzhi** [comment]
[wangyongzhi](https://github.com/wangyongzhi)，thx

**Comment by bblu** [comment]
bblu， thanks

**Comment by custa** [comment]
custa, thx

**Comment by GARENFEATHER** [comment]
GARENFEATHER, thx mate

**Comment by phpdpy** [comment]
phpdpy,thx

**Comment by 5ispy** [comment]
5ispy,thanks

**Comment by WenHaiGo** [comment]
WenHaiGo, thanks

**Comment by tiod** [comment]
tiod, 3q😁

**Comment by tobinwang** [comment]
tobinwang，thanks

**Comment by dhttony** [comment]
dhttony, thanks!

**Comment by BiaogeTwo** [comment]
BiaogeTwo，thx

**Comment by phpdpy** [comment]
invite me thank you！

**Comment by mengxiangjian13** [comment]
Please invite me. Thanks!

**Comment by gejun1979** [comment]
gejun1979, thanks!

**Comment by fireflyEngineer** [comment]
I'm in the communication group. Invite me please, thx.

**Comment by fireflyEngineer** [comment]
fireflyEngineer

**Comment by daxiangxiaoyi** [comment]
daxiangxiaoyi，thx

**Comment by RaymondNY** [comment]
RaymondNY,thx

**Comment by dentalulcer** [comment]
dentalulcer

**Comment by fatyu** [comment]
fatyu,thx

**Comment by hushulei** [comment]
hushulei， thx

**Comment by haoel** [comment]
haoel

**Comment by bob-chen** [comment]
bob-chen ,thx

**Comment by Alex0xf** [comment]
Alex0xf,thx

**Comment by echofoo** [comment]
echofoo, thx

**Comment by gmzhang** [comment]
gmzhang, thx

**Comment by jenenliu** [comment]
[jenenliu](https://github.com/jenenliu) , thanks

**Comment by PoacherBro** [comment]
poacherbro, thanks

**Comment by lbf1121** [comment]
lbf1121，thanks

**Comment by zealoussnow** [comment]
zealoussnow, thanks

**Comment by tiancy** [comment]
tiancy, thx

**Comment by MarsForever** [comment]
MarsForever,thanks

**Comment by Daheyoyo** [comment]
Daheyoyo,thanks

**Comment by zeahoo** [comment]
Zeahoo, Thank you.

**Comment by AngiesEmail** [comment]
AngiesEmail，Thank you.

**Comment by gmg0829** [comment]
gmg0829,thank you .
